### ISSUE TITLE
V1.0 causes Player's to get disconnected on a server but doesn't throw an error.

### ISSUE THREAD

**Issue by netcore10** [GmsGarcia/decor4fabric#1]
I've tested in all cases, clients are fine, but if 1.0 is used on a server, player's get disconnected on a server the moment they join world.

**Comment by GmsGarcia** [comment]
Hi! Are the client & server using the same version?
That's probably the error. I fixed it in the past, but I'll check it out again.

For further support I'll advice you to join my discord server. There I can help more quickly.

**Comment by netcore10** [comment]
They are indeed, the moment we go to 1.0, clients get booted (it looks to be you get a split second of seeing the world) I'll join the discord

**Comment by V-lpen** [comment]
Experiencing the same issue here
on 1.1 both client and server

**Comment by GmsGarcia** [comment]
This issue has been fixed in v1.2. I'll release it soon. :)
