### ISSUE TITLE
Unable to resolve texture reference

### ISSUE THREAD

**Issue by TheButterbrotMan** [GmsGarcia/decor4fabric#3]
https://bytebin.lucko.me/cFEIpkPLvn

decor4fabric-1.2.1-1.18.2.jar

**Comment by GmsGarcia** [comment]
Hi! I aware of this warning... But as I said, it's just a warning, it should work perfectly aswell...

**Comment by TheButterbrotMan** [comment]
Would just be nice to have a clean log. Lololol.

**Comment by GmsGarcia** [comment]
Hi @TheButterbrotMan! I'll check into it and I'll try to remove it :)
I noticed you join our Discord, so the moment I release a version with this fix, you'll get informed :))

Greetings, gmsg4rcia :))
