### ISSUE TITLE
Port to 1.16.5

### ISSUE THREAD

**Issue by sleepysapph** [GmsGarcia/decor4fabric#4]
Hiya! Really stupid request but this mods features are above and beyond! However a lot of awesome Fabric mods have ended their development with 1.16.5, and so I can't upgrade a server I've had with friends to 1.17, therefore we can't use this mod :/ (not to mention that some folks aren't a fan of changes that came in Caves and Cliffs)

I have no idea how realistic this is or not, especially since 1.16.5 is awhile ago, but yeah. Thanks for taking it into account :D

**Comment by GmsGarcia** [comment]
Hi @sleepysapph! I'm thinking about porting it to 1.16.5 soon (as soon as I finish porting it to **Forge** versions). You can join my **[Discord server](https://discord.gmsgarcia.ga)** to get the latest updates on the mod.

Greetings, gmsg4rci4 :))

**Comment by sleepysapph** [comment]
Wonderful! Just joined the discord :) Thanks so much
